version: '3.8'

services:
    web:
        build: ./voice-trace-ui
        ports:
            - 3000:3000
        environment:
            DB_URL: mongodb://db/db_name
        depends_on:
            - db 

    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        volumes:
            -vidly:/data/db

volumes:
    vidly:
